Added publish dependencies for ios
appcircleio/appcircle-publishflow-components pull request #102
Opened 2024-06-05 10:44 UTC by boztopuz

2024-06-05 16:14 UTC, ftmzhrsckldr requested changes

2024-06-05 16:14 UTC, ftmzhrsckldr commented on appcircle_publish_send_to_testflight/1.2.1/component.yaml
> +precedingComponents: "appcircle_publish_appstore_app_information"
Why we need to add this step after the appcircle_publish_appstore_app_information step?

2024-06-05 16:14 UTC, ftmzhrsckldr commented on appcircle_publish_testflight_status_check/1.1.1/component.yaml
> +precedingComponents: "appcircle_publish_appstore_app_information"
Why we need to add this step after the appcircle_publish_appstore_app_information step?

2024-06-06 08:01 UTC, boztopuz commented on appcircle_publish_send_to_appstore/1.2.1/component.yaml
> +precedingComponents: "appcircle_publish_send_to_testflight,appcircle_publish_testflight_status_check,appcircle_publish_appstore_app_information"
Actually, email approval step is common step, I think it should be free in the flow.

2024-06-06 08:02 UTC, boztopuz commented on appcircle_publish_appstore_status_check/1.0.1/component.yaml
> +docsUrl: https://github.com/appcircleio/appcircle-publish-appstore-status-check
Yes I know, but the doc is missing. I fix the doc and then I changed the doc link.

2024-06-06 09:20 UTC, ftmzhrsckldr commented on appcircle_publish_send_to_appstore/1.2.1/component.yaml
> +commit: 11e6ef4
Commit id not same the last commit ID, is that any reason?

2024-06-06 09:20 UTC, ftmzhrsckldr commented on appcircle_custom_script/1.0.2/component.yaml
> +commit: c163e15
Commit id not same the last commit ID, is that any reason?

2024-06-06 09:39 UTC, merged